// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace SunpathDiagram
{
    public class SunpathDiagramOutputs: ResultsBase
    {
		/// <summary>
		/// The time zone for this location
		/// </summary>
		[JsonProperty("Time Zone")]
		public string TimeZone {get; set;}



        /// <summary>
        /// Construct a SunpathDiagramOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public SunpathDiagramOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a SunpathDiagramOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public SunpathDiagramOutputs(string timeZone): base()
        {
			this.TimeZone = timeZone;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}